### ISSUE TITLE
Rate a Refran

### ISSUE THREAD

**Issue by Ironjanowar** [Ironjanowar/refraner_bot#1]
There is already a rate button so, just implement it!

![image](https://user-images.githubusercontent.com/9699815/37337370-57542182-26b4-11e8-9522-85c4698e3d29.png)

After clicking on it, the keyboard should change to 6 buttons, something like this:

```
|------------|
| ⭐️          |
|------------|
| ⭐️⭐️         |
|------------|
| ⭐️⭐️⭐️        |
|------------|
| ⭐️⭐️⭐️⭐️       |
|------------|
| ⭐️⭐️⭐️⭐️⭐️      |
|------------|
| Cancel     |
|------------|
```

Ratings will be saved and should be stored in... maybe... the `refranes.json` ??

**Comment by AshidaSRS** [comment]
Instead of a button that expands to 6 buttons, maybe put 6 buttons in the bottom will be better. Like:
```
+---------------------------------------+
|         Hide / Show                   |
+---+----+-----+------+-------+---------+
| * | ** | *** | **** | ***** | ******  |
+---+----+-----+------+-------+---------+
```
With only one choice per user in the rate buttons.

**Comment by Ironjanowar** [comment]
Hmmmmmm, 6 buttons in a row may be too mutch, I don't know if the 5 stars button would show all 5 starts. I also wanted to **change** the keyboard in order to separate functionalities. Something like `"You are now rating, so pick something dude"`.

**Comment by Ironjanowar** [comment]
As @AshidaSRS suggested me I'll use this icons in a single row:

☹️ 😕 😐 😀 😁

**Comment by Ironjanowar** [comment]
![image](https://user-images.githubusercontent.com/9699815/37340512-aa2fe832-26be-11e8-9ccb-0c84ee388e3f.png)

**Comment by Ironjanowar** [comment]
![image](https://user-images.githubusercontent.com/9699815/37343420-cdc2e61a-26c7-11e8-8e73-88a76180d7ae.png)

**Comment by Ironjanowar** [comment]
Think of a way to show that the user voted
