### ISSUE TITLE
Update to ExGram

### ISSUE THREAD

**Issue by Ironjanowar** [Ironjanowar/refraner_bot#16]
![image](https://user-images.githubusercontent.com/9699815/53523424-1110ae00-3add-11e9-9f4a-ad12041645c3.png)

**Comment by rockneurotiko** [comment]
JAJAJAJAJAJA #RockApproves

**Comment by Ironjanowar** [comment]
Ay lmao, I did not remember the meme :joy:

**Comment by rockneurotiko** [comment]
Epic 😂😂
